# Generated by Django 4.2.9 on 2024-01-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('area', models.CharField(max_length=30, null=True)),
                ('dob', models.DateField()),
                ('description', models.CharField(max_length=400, null=True)),
                ('department', models.CharField(max_length=30)),
                ('designation', models.CharField(choices=[('consultant', 'Consultant'), ('senior_consultant', 'Senior Consultant'), ('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor')], max_length=25)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Consultency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=4)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultency', to='doctors.doctor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='consultency',
            constraint=models.UniqueConstraint(fields=('doctor', 'clinic', 'room'), name='unique_doctor_clinic_room'),
        ),
    ]
