# Generated by Django 4.2.9 on 2024-01-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor', 'date'), name='unique_patient_doctor_date'),
        ),
    ]
