# Generated by Django 4.2.9 on 2024-01-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_consultencyday_unique_consultency_day'),
        ('patients', '0004_alter_speciality_unique_together_and_more'),
        ('treatments', '0002_request_unique_patient_doctor_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('success', 'Success'), ('failure', 'Failure')], default='ongoing', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('last_date', models.DateField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.AddConstraint(
            model_name='treatment',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor', 'disease', 'start_date'), name='unique_patient_doctor_disease_start_date'),
        ),
    ]
